services:  

  agric_api:
    container_name: agric_api.prod
    image: agric_api.prod:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
