# Generated by Django 5.2.3 on 2025-06-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('cpf_cnpj', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=10)),
                ('nome_produtor', models.CharField(max_length=255)),
            ],
        ),
    ]
