# Generated by Django 5.2.3 on 2025-06-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtor',
            table='produtor',
        ),
    ]
