# Generated by Django 5.2.3 on 2025-06-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0002_alter_produtor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_estado', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
    ]
