# Generated by Django 5.2.3 on 2025-06-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0003_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='agric.estado')),
            ],
            options={
                'db_table': 'cidade',
                'unique_together': {('nome_cidade', 'estado')},
            },
        ),
    ]
