# Generated by Django 5.2.3 on 2025-06-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0004_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCultura',
            fields=[
                ('id_tipo_cultura', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cultura', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tipo_cultura',
            },
        ),
    ]
