# Generated by Django 5.2.3 on 2025-06-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0005_tipocultura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id_propriedade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_propriedade', models.CharField(max_length=255)),
                ('area_total', models.FloatField()),
                ('area_agricultavel', models.FloatField()),
                ('area_vegetacao', models.FloatField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='agric.cidade')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='agric.produtor')),
            ],
            options={
                'db_table': 'propriedade',
            },
        ),
    ]
