# Generated by Django 5.2.3 on 2025-06-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0006_propriedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id_cultura', models.BigAutoField(primary_key=True, serialize=False)),
                ('ano_safra', models.IntegerField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='agric.propriedade')),
                ('tipo_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='agric.tipocultura')),
            ],
            options={
                'db_table': 'cultura',
                'unique_together': {('ano_safra', 'tipo_cultura', 'propriedade')},
            },
        ),
    ]
